adding documentation for the new write_kubeconfig property
civo/terraform-provider-civo pull request #321
Opened 2024-08-13 19:52 UTC by johndietz

need docs to use new property introduced in 1.1.0 of civo provider

2024-08-14 09:58 UTC, uzaxirr requested changes

2024-08-14 09:58 UTC, uzaxirr commented on docs/resources/kubernetes_cluster.md
> +- `write_kubeconfig` (Boolean) (false by default) set to true to allow setting the cluster's kubeconfig property
It should be 

- `write_kubeconfig` (Boolean) (false by default) when set to true kubeconfig is saved to the terraform state file

2024-08-16 12:21 UTC, fernando-villalba approved these changes

2024-08-16 15:28 UTC, johndietz commented
just circling back, wanted to say thanks for the tweaked commit @fernando-villalba

2024-08-20 07:35 UTC, uzaxirr approved these changes

2024-08-20 07:35 UTC, merged